# Generated by Django 4.2.16 on 2024-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
