# Generated by Django 4.2.16 on 2024-12-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_comment_approved_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
