# Generated by Django 4.2.16 on 2024-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_comment_likes_review_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
